insert into public.tests (id, title, subject, level, status, total_points, app_path)
values
  ('summer-math-level-1-pretest', 'Summer Math Level 1 Pre-test', 'Math', 'Summer Math Level 1', 'inactive', 30, '/tests/summer-math-level-1-pretest/start'),
  ('summer-math-level-2-pretest', 'Summer Math Level 2 Pre-test', 'Math', 'Summer Math Level 2', 'inactive', 30, '/tests/summer-math-level-2-pretest/start'),
  ('summer-math-level-3-pretest', 'Summer Math Level 3 Pre-test', 'Math', 'Summer Math Level 3', 'inactive', 30, '/tests/summer-math-level-3-pretest/start')
on conflict (id) do update set
  title = excluded.title,
  subject = excluded.subject,
  level = excluded.level,
  status = excluded.status,
  total_points = excluded.total_points,
  app_path = excluded.app_path;

insert into public.test_questions (id, test_id, part, prompt, answer_key, transcript_ref, points, position)
values
  ('summer-math-level-1-q1', 'summer-math-level-1-pretest', 'Part I', '2, 4, __, 8, __', '{"source":"mathMultiPart","display":"6, 10","parts":[{"id":"a","accepted":["6"],"points":0.5},{"id":"b","accepted":["10"],"points":0.5}]}'::jsonb, null, 1, 1),
  ('summer-math-level-1-q2', 'summer-math-level-1-pretest', 'Part I', '__, 25, 30, __, 40', '{"source":"mathMultiPart","display":"20, 35","parts":[{"id":"a","accepted":["20"],"points":0.5},{"id":"b","accepted":["35"],"points":0.5}]}'::jsonb, null, 1, 2),
  ('summer-math-level-1-q3', 'summer-math-level-1-pretest', 'Part I', '__, 20, __, 40, 50', '{"source":"mathMultiPart","display":"10, 30","parts":[{"id":"a","accepted":["10"],"points":0.5},{"id":"b","accepted":["30"],"points":0.5}]}'::jsonb, null, 1, 3),
  ('summer-math-level-1-q4', 'summer-math-level-1-pretest', 'Part II', '12 + 4 =', '{"source":"mathMultiPart","display":"16","parts":[{"id":"answer","accepted":["16"],"points":1}]}'::jsonb, null, 1, 4),
  ('summer-math-level-1-q5', 'summer-math-level-1-pretest', 'Part II', '20 + 6 =', '{"source":"mathMultiPart","display":"26","parts":[{"id":"answer","accepted":["26"],"points":1}]}'::jsonb, null, 1, 5),
  ('summer-math-level-1-q6', 'summer-math-level-1-pretest', 'Part II', '8 + 7 =', '{"source":"mathMultiPart","display":"15","parts":[{"id":"answer","accepted":["15"],"points":1}]}'::jsonb, null, 1, 6),
  ('summer-math-level-1-q7', 'summer-math-level-1-pretest', 'Part III', '15 - 1 =', '{"source":"mathMultiPart","display":"14","parts":[{"id":"answer","accepted":["14"],"points":1}]}'::jsonb, null, 1, 7),
  ('summer-math-level-1-q8', 'summer-math-level-1-pretest', 'Part III', '28 - 4 =', '{"source":"mathMultiPart","display":"24","parts":[{"id":"answer","accepted":["24"],"points":1}]}'::jsonb, null, 1, 8),
  ('summer-math-level-1-q9', 'summer-math-level-1-pretest', 'Part III', '10 - 3 =', '{"source":"mathMultiPart","display":"7","parts":[{"id":"answer","accepted":["7"],"points":1}]}'::jsonb, null, 1, 9),
  ('summer-math-level-1-q10', 'summer-math-level-1-pretest', 'Part IV', 'Which dessert is displayed the least?', '{"source":"mathMultiPart","display":"Cake","parts":[{"id":"answer","accepted":["cake"],"points":1}]}'::jsonb, null, 1, 10),
  ('summer-math-level-1-q11', 'summer-math-level-1-pretest', 'Part IV', 'How many pieces of macaron are displayed?', '{"source":"mathMultiPart","display":"7","parts":[{"id":"answer","accepted":["7"],"points":1}]}'::jsonb, null, 1, 11),
  ('summer-math-level-1-q12', 'summer-math-level-1-pretest', 'Part IV', 'Which dessert counts to 9?', '{"source":"mathMultiPart","display":"Cupcake","parts":[{"id":"answer","accepted":["cupcake","cupcakes"],"points":1}]}'::jsonb, null, 1, 12),
  ('summer-math-level-1-q13', 'summer-math-level-1-pretest', 'Part IV', 'Which dessert counts to 8?', '{"source":"mathMultiPart","display":"Cookie","parts":[{"id":"answer","accepted":["cookie","cookies"],"points":1}]}'::jsonb, null, 1, 13),
  ('summer-math-level-1-q14', 'summer-math-level-1-pretest', 'Part IV', 'How many cherries are topped in each cupcake?', '{"source":"mathMultiPart","display":"1","parts":[{"id":"answer","accepted":["1","one"],"points":1}]}'::jsonb, null, 1, 14),
  ('summer-math-level-1-q15', 'summer-math-level-1-pretest', 'Part IV', 'How many desserts are there altogether?', '{"source":"mathMultiPart","display":"30","parts":[{"id":"answer","accepted":["30"],"points":1}]}'::jsonb, null, 1, 15),
  ('summer-math-level-1-q16', 'summer-math-level-1-pretest', 'Part V', '12 is ___ than 13.', '{"source":"mathMultiPart","display":"smaller","parts":[{"id":"answer","accepted":["smaller","less"],"points":1}]}'::jsonb, null, 1, 16),
  ('summer-math-level-1-q17', 'summer-math-level-1-pretest', 'Part V', '57 is ___ than 48.', '{"source":"mathMultiPart","display":"greater","parts":[{"id":"answer","accepted":["greater","bigger","larger"],"points":1}]}'::jsonb, null, 1, 17),
  ('summer-math-level-1-q18', 'summer-math-level-1-pretest', 'Part V', '10 is ___ than 100.', '{"source":"mathMultiPart","display":"smaller","parts":[{"id":"answer","accepted":["smaller","less"],"points":1}]}'::jsonb, null, 1, 18),
  ('summer-math-level-1-q19', 'summer-math-level-1-pretest', 'Part V', '66 is ___ than 56.', '{"source":"mathMultiPart","display":"greater","parts":[{"id":"answer","accepted":["greater","bigger","larger"],"points":1}]}'::jsonb, null, 1, 19),
  ('summer-math-level-1-q20', 'summer-math-level-1-pretest', 'Part V', '18 is ___ than 81.', '{"source":"mathMultiPart","display":"smaller","parts":[{"id":"answer","accepted":["smaller","less"],"points":1}]}'::jsonb, null, 1, 20),
  ('summer-math-level-1-q21', 'summer-math-level-1-pretest', 'Part VI', 'Clock 1', '{"source":"mathMultiPart","display":"6:30","parts":[{"id":"answer","accepted":["6:30","6.30","6 30","six thirty"],"points":1,"normalizer":"time"}]}'::jsonb, null, 1, 21),
  ('summer-math-level-1-q22', 'summer-math-level-1-pretest', 'Part VI', 'Clock 2', '{"source":"mathMultiPart","display":"4:00","parts":[{"id":"answer","accepted":["4:00","4.00","4","4 00","four oclock"],"points":1,"normalizer":"time"}]}'::jsonb, null, 1, 22),
  ('summer-math-level-1-q23', 'summer-math-level-1-pretest', 'Part VI', 'Clock 3', '{"source":"mathMultiPart","display":"1:45","parts":[{"id":"answer","accepted":["1:45","1.45","1 45","one forty five"],"points":1,"normalizer":"time"}]}'::jsonb, null, 1, 23),
  ('summer-math-level-1-q24', 'summer-math-level-1-pretest', 'Part VII', '8', '{"source":"mathMultiPart","display":"eight","parts":[{"id":"answer","accepted":["eight"],"points":1}]}'::jsonb, null, 1, 24),
  ('summer-math-level-1-q25', 'summer-math-level-1-pretest', 'Part VII', '12', '{"source":"mathMultiPart","display":"twelve","parts":[{"id":"answer","accepted":["twelve"],"points":1}]}'::jsonb, null, 1, 25),
  ('summer-math-level-1-q26', 'summer-math-level-1-pretest', 'Part VII', '21', '{"source":"mathMultiPart","display":"twenty one","parts":[{"id":"answer","accepted":["twenty one","twenty-one"],"points":1}]}'::jsonb, null, 1, 26),
  ('summer-math-level-1-q27', 'summer-math-level-1-pretest', 'Part VII', '14', '{"source":"mathMultiPart","display":"fourteen","parts":[{"id":"answer","accepted":["fourteen"],"points":1}]}'::jsonb, null, 1, 27),
  ('summer-math-level-1-q28', 'summer-math-level-1-pretest', 'Part VIII', 'Thirty two =', '{"source":"mathMultiPart","display":"32","parts":[{"id":"answer","accepted":["32"],"points":1}]}'::jsonb, null, 1, 28),
  ('summer-math-level-1-q29', 'summer-math-level-1-pretest', 'Part VIII', 'Seventy six =', '{"source":"mathMultiPart","display":"76","parts":[{"id":"answer","accepted":["76"],"points":1}]}'::jsonb, null, 1, 29),
  ('summer-math-level-1-q30', 'summer-math-level-1-pretest', 'Part VIII', 'Fifty one =', '{"source":"mathMultiPart","display":"51","parts":[{"id":"answer","accepted":["51"],"points":1}]}'::jsonb, null, 1, 30),
  ('summer-math-level-2-q1', 'summer-math-level-2-pretest', 'Part I', '52 x 3 =', '{"source":"mathMultiPart","display":"156","parts":[{"id":"answer","accepted":["156"],"points":1}]}'::jsonb, null, 1, 1),
  ('summer-math-level-2-q2', 'summer-math-level-2-pretest', 'Part I', '123 x 2 =', '{"source":"mathMultiPart","display":"246","parts":[{"id":"answer","accepted":["246"],"points":1}]}'::jsonb, null, 1, 2),
  ('summer-math-level-2-q3', 'summer-math-level-2-pretest', 'Part I', '404 x 5 =', '{"source":"mathMultiPart","display":"2,020","parts":[{"id":"answer","accepted":["2020","2,020"],"points":1}]}'::jsonb, null, 1, 3),
  ('summer-math-level-2-q4', 'summer-math-level-2-pretest', 'Part I', '11 x 6 =', '{"source":"mathMultiPart","display":"66","parts":[{"id":"answer","accepted":["66"],"points":1}]}'::jsonb, null, 1, 4),
  ('summer-math-level-2-q5', 'summer-math-level-2-pretest', 'Part II', '910', '{"source":"mathMultiPart","display":"900 + 10","parts":[{"id":"answer","accepted":["900 + 10","900+10","900 + 10 + 0","900+10+0"],"points":1}]}'::jsonb, null, 1, 5),
  ('summer-math-level-2-q6', 'summer-math-level-2-pretest', 'Part II', '7,108', '{"source":"mathMultiPart","display":"7,000 + 100 + 8","parts":[{"id":"answer","accepted":["7000 + 100 + 8","7000+100+8","7,000 + 100 + 8","7,000+100+8"],"points":1}]}'::jsonb, null, 1, 6),
  ('summer-math-level-2-q7', 'summer-math-level-2-pretest', 'Part II', '10,375', '{"source":"mathMultiPart","display":"10,000 + 300 + 70 + 5","parts":[{"id":"answer","accepted":["10000 + 300 + 70 + 5","10000+300+70+5","10,000 + 300 + 70 + 5","10,000+300+70+5"],"points":1}]}'::jsonb, null, 1, 7),
  ('summer-math-level-2-q8', 'summer-math-level-2-pretest', 'Part III', '42 / 7 =', '{"source":"mathMultiPart","display":"6","parts":[{"id":"answer","accepted":["6"],"points":1}]}'::jsonb, null, 1, 8),
  ('summer-math-level-2-q9', 'summer-math-level-2-pretest', 'Part III', '25 / 5 =', '{"source":"mathMultiPart","display":"5","parts":[{"id":"answer","accepted":["5"],"points":1}]}'::jsonb, null, 1, 9),
  ('summer-math-level-2-q10', 'summer-math-level-2-pretest', 'Part III', '15 / 3 =', '{"source":"mathMultiPart","display":"5","parts":[{"id":"answer","accepted":["5"],"points":1}]}'::jsonb, null, 1, 10),
  ('summer-math-level-2-q11', 'summer-math-level-2-pretest', 'Part IV', '72,380 rounded to the underlined hundreds digit', '{"source":"mathMultiPart","display":"72,400","parts":[{"id":"answer","accepted":["72400","72,400"],"points":1}]}'::jsonb, null, 1, 11),
  ('summer-math-level-2-q12', 'summer-math-level-2-pretest', 'Part IV', '2,624 rounded to the underlined thousands digit', '{"source":"mathMultiPart","display":"3,000","parts":[{"id":"answer","accepted":["3000","3,000"],"points":1}]}'::jsonb, null, 1, 12),
  ('summer-math-level-2-q13', 'summer-math-level-2-pretest', 'Part IV', '429 rounded to the underlined ones digit', '{"source":"mathMultiPart","display":"429","parts":[{"id":"answer","accepted":["429"],"points":1}]}'::jsonb, null, 1, 13),
  ('summer-math-level-2-q14', 'summer-math-level-2-pretest', 'Part IV', '10,256 rounded to the underlined thousands digit', '{"source":"mathMultiPart","display":"10,000","parts":[{"id":"answer","accepted":["10000","10,000"],"points":1}]}'::jsonb, null, 1, 14),
  ('summer-math-level-2-q15', 'summer-math-level-2-pretest', 'Part IV', '9,991 rounded to the underlined tens digit', '{"source":"mathMultiPart","display":"9,990","parts":[{"id":"answer","accepted":["9990","9,990"],"points":1}]}'::jsonb, null, 1, 15),
  ('summer-math-level-2-q16', 'summer-math-level-2-pretest', 'Part V', 'Which team won the contest?', '{"source":"mathMultiPart","display":"Team H","parts":[{"id":"answer","accepted":["Team H","H"],"points":1}]}'::jsonb, null, 1, 16),
  ('summer-math-level-2-q17', 'summer-math-level-2-pretest', 'Part V', 'How many points did Team F score?', '{"source":"mathMultiPart","display":"50","parts":[{"id":"answer","accepted":["50"],"points":1}]}'::jsonb, null, 1, 17),
  ('summer-math-level-2-q18', 'summer-math-level-2-pretest', 'Part V', 'How many more points did Team D score than Team G?', '{"source":"mathMultiPart","display":"40","parts":[{"id":"answer","accepted":["40"],"points":1}]}'::jsonb, null, 1, 18),
  ('summer-math-level-2-q19', 'summer-math-level-2-pretest', 'Part V', 'Which teams scored equally?', '{"source":"mathMultiPart","display":"Team C and Team F","parts":[{"id":"answer","accepted":["Team C and Team F","C and F","Team F and Team C","F and C"],"points":1}]}'::jsonb, null, 1, 19),
  ('summer-math-level-2-q20', 'summer-math-level-2-pretest', 'Part V', 'How many teams scored less than 100 points?', '{"source":"mathMultiPart","display":"6","parts":[{"id":"answer","accepted":["6"],"points":1}]}'::jsonb, null, 1, 20),
  ('summer-math-level-2-q21', 'summer-math-level-2-pretest', 'Part VI', 'Describe these lines.', '{"source":"mathMultiPart","display":"parallel","parts":[{"id":"answer","accepted":["parallel"],"points":1}]}'::jsonb, null, 1, 21),
  ('summer-math-level-2-q22', 'summer-math-level-2-pretest', 'Part VI', 'Describe these lines.', '{"source":"mathMultiPart","display":"intersecting","parts":[{"id":"answer","accepted":["intersecting"],"points":1}]}'::jsonb, null, 1, 22),
  ('summer-math-level-2-q23', 'summer-math-level-2-pretest', 'Part VI', 'Describe these lines.', '{"source":"mathMultiPart","display":"perpendicular","parts":[{"id":"answer","accepted":["perpendicular"],"points":1}]}'::jsonb, null, 1, 23),
  ('summer-math-level-2-q24', 'summer-math-level-2-pretest', 'Part VII', 'What fraction is shaded?', '{"source":"mathMultiPart","display":"1/3","parts":[{"id":"answer","accepted":["1/3"],"points":1}]}'::jsonb, null, 1, 24),
  ('summer-math-level-2-q25', 'summer-math-level-2-pretest', 'Part VII', 'What fraction is shaded?', '{"source":"mathMultiPart","display":"2/5","parts":[{"id":"answer","accepted":["2/5"],"points":1}]}'::jsonb, null, 1, 25),
  ('summer-math-level-2-q26', 'summer-math-level-2-pretest', 'Part VII', 'What fraction is shaded?', '{"source":"mathMultiPart","display":"2/10","parts":[{"id":"answer","accepted":["2/10","1/5"],"points":1}]}'::jsonb, null, 1, 26),
  ('summer-math-level-2-q27', 'summer-math-level-2-pretest', 'Part VIII', '2/4 ___ 1/4', '{"source":"mathMultiPart","display":">","parts":[{"id":"answer","accepted":["gt"],"points":1}]}'::jsonb, null, 1, 27),
  ('summer-math-level-2-q28', 'summer-math-level-2-pretest', 'Part VIII', '3/10 ___ 8/10', '{"source":"mathMultiPart","display":"<","parts":[{"id":"answer","accepted":["lt"],"points":1}]}'::jsonb, null, 1, 28),
  ('summer-math-level-2-q29', 'summer-math-level-2-pretest', 'Part VIII', '1/2 ___ 2/4', '{"source":"mathMultiPart","display":"=","parts":[{"id":"answer","accepted":["eq"],"points":1}]}'::jsonb, null, 1, 29),
  ('summer-math-level-2-q30', 'summer-math-level-2-pretest', 'Part VIII', '7/7 ___ 1/8', '{"source":"mathMultiPart","display":">","parts":[{"id":"answer","accepted":["gt"],"points":1}]}'::jsonb, null, 1, 30),
  ('summer-math-level-3-q1', 'summer-math-level-3-pretest', 'Part I', '102 - 38 - 43 =', '{"source":"mathMultiPart","display":"21","parts":[{"id":"answer","accepted":["21"],"points":1}]}'::jsonb, null, 1, 1),
  ('summer-math-level-3-q2', 'summer-math-level-3-pretest', 'Part I', '322 + 98 / 7 - 130 =', '{"source":"mathMultiPart","display":"206","parts":[{"id":"answer","accepted":["206"],"points":1}]}'::jsonb, null, 1, 2),
  ('summer-math-level-3-q3', 'summer-math-level-3-pretest', 'Part I', '15,000 / 3,000 + 12 =', '{"source":"mathMultiPart","display":"17","parts":[{"id":"answer","accepted":["17"],"points":1}]}'::jsonb, null, 1, 3),
  ('summer-math-level-3-q4', 'summer-math-level-3-pretest', 'Part I', '187 x 4,000 =', '{"source":"mathMultiPart","display":"748,000","parts":[{"id":"answer","accepted":["748000","748,000"],"points":1}]}'::jsonb, null, 1, 4),
  ('summer-math-level-3-q5', 'summer-math-level-3-pretest', 'Part I', '1,750 / 50 =', '{"source":"mathMultiPart","display":"35","parts":[{"id":"answer","accepted":["35"],"points":1}]}'::jsonb, null, 1, 5),
  ('summer-math-level-3-q6', 'summer-math-level-3-pretest', 'Part II', '5,190,000 = ___ + 100,000 + 20,000 + 9,000', '{"source":"mathMultiPart","display":"5,000,000","parts":[{"id":"answer","accepted":["5000000","5,000,000"],"points":1}]}'::jsonb, null, 1, 6),
  ('summer-math-level-3-q7', 'summer-math-level-3-pretest', 'Part II', '1,003,900 = 1,000,000 + ___ + 900', '{"source":"mathMultiPart","display":"3,000","parts":[{"id":"answer","accepted":["3000","3,000"],"points":1}]}'::jsonb, null, 1, 7),
  ('summer-math-level-3-q8', 'summer-math-level-3-pretest', 'Part II', 'In 4,835,400, the digit 8 stands for ___.', '{"source":"mathMultiPart","display":"800,000","parts":[{"id":"answer","accepted":["800000","800,000","eight hundred thousand"],"points":1}]}'::jsonb, null, 1, 8),
  ('summer-math-level-3-q9', 'summer-math-level-3-pretest', 'Part II', 'In 8,721,650, the digit 8 stands for ___.', '{"source":"mathMultiPart","display":"8,000,000","parts":[{"id":"answer","accepted":["8000000","8,000,000","eight million"],"points":1}]}'::jsonb, null, 1, 9),
  ('summer-math-level-3-q10', 'summer-math-level-3-pretest', 'Part II', 'Find the sum of 80,400 and 9,000 and round off the answer to the nearest thousand.', '{"source":"mathMultiPart","display":"89,000","parts":[{"id":"answer","accepted":["89000","89,000"],"points":1}]}'::jsonb, null, 1, 10),
  ('summer-math-level-3-q11', 'summer-math-level-3-pretest', 'Part III', '17/100', '{"source":"mathMultiPart","display":"17%","parts":[{"id":"answer","accepted":["17","17%"],"points":1}]}'::jsonb, null, 1, 11),
  ('summer-math-level-3-q12', 'summer-math-level-3-pretest', 'Part III', '25/100', '{"source":"mathMultiPart","display":"25%","parts":[{"id":"answer","accepted":["25","25%"],"points":1}]}'::jsonb, null, 1, 12),
  ('summer-math-level-3-q13', 'summer-math-level-3-pretest', 'Part III', '4/5', '{"source":"mathMultiPart","display":"80%","parts":[{"id":"answer","accepted":["80","80%"],"points":1}]}'::jsonb, null, 1, 13),
  ('summer-math-level-3-q14', 'summer-math-level-3-pretest', 'Part IV', '9/10', '{"source":"mathMultiPart","display":"0.9","parts":[{"id":"answer","accepted":["0.9",".9"],"points":1}]}'::jsonb, null, 1, 14),
  ('summer-math-level-3-q15', 'summer-math-level-3-pretest', 'Part IV', '23/100', '{"source":"mathMultiPart","display":"0.23","parts":[{"id":"answer","accepted":["0.23",".23"],"points":1}]}'::jsonb, null, 1, 15),
  ('summer-math-level-3-q16', 'summer-math-level-3-pretest', 'Part V', '2 2/5 + 1 1/5 =', '{"source":"mathMultiPart","display":"3 3/5","parts":[{"id":"answer","accepted":["3 3/5","18/5"],"points":1}]}'::jsonb, null, 1, 16),
  ('summer-math-level-3-q17', 'summer-math-level-3-pretest', 'Part V', '3 1/6 + 1 2/3 =', '{"source":"mathMultiPart","display":"4 5/6","parts":[{"id":"answer","accepted":["4 5/6","29/6"],"points":1}]}'::jsonb, null, 1, 17),
  ('summer-math-level-3-q18', 'summer-math-level-3-pretest', 'Part V', '4 - 3 2/3 =', '{"source":"mathMultiPart","display":"1/3","parts":[{"id":"answer","accepted":["1/3"],"points":1}]}'::jsonb, null, 1, 18),
  ('summer-math-level-3-q19', 'summer-math-level-3-pretest', 'Part V', '2 11/12 - 1 1/6 =', '{"source":"mathMultiPart","display":"1 3/4","parts":[{"id":"answer","accepted":["1 3/4","7/4"],"points":1}]}'::jsonb, null, 1, 19),
  ('summer-math-level-3-q20', 'summer-math-level-3-pretest', 'Part V', '9/10 x 2/3 =', '{"source":"mathMultiPart","display":"3/5","parts":[{"id":"answer","accepted":["3/5"],"points":1}]}'::jsonb, null, 1, 20),
  ('summer-math-level-3-q21', 'summer-math-level-3-pretest', 'Part VI', 'Identify the angle.', '{"source":"mathMultiPart","display":"acute","parts":[{"id":"answer","accepted":["acute"],"points":1}]}'::jsonb, null, 1, 21),
  ('summer-math-level-3-q22', 'summer-math-level-3-pretest', 'Part VI', 'Identify the angle.', '{"source":"mathMultiPart","display":"right","parts":[{"id":"answer","accepted":["right"],"points":1}]}'::jsonb, null, 1, 22),
  ('summer-math-level-3-q23', 'summer-math-level-3-pretest', 'Part VI', 'Identify the angle.', '{"source":"mathMultiPart","display":"obtuse","parts":[{"id":"answer","accepted":["obtuse"],"points":1}]}'::jsonb, null, 1, 23),
  ('summer-math-level-3-q24', 'summer-math-level-3-pretest', 'Part VII', '3y = 15. y =', '{"source":"mathMultiPart","display":"5","parts":[{"id":"answer","accepted":["5"],"points":1}]}'::jsonb, null, 1, 24),
  ('summer-math-level-3-q25', 'summer-math-level-3-pretest', 'Part VII', '5y = 60. y =', '{"source":"mathMultiPart","display":"12","parts":[{"id":"answer","accepted":["12"],"points":1}]}'::jsonb, null, 1, 25),
  ('summer-math-level-3-q26', 'summer-math-level-3-pretest', 'Part VIII', 'How many donut boxes did she sell in week 3?', '{"source":"mathMultiPart","display":"150","parts":[{"id":"answer","accepted":["150"],"points":1}]}'::jsonb, null, 1, 26),
  ('summer-math-level-3-q27', 'summer-math-level-3-pretest', 'Part VIII', 'Which week did she sell the least?', '{"source":"mathMultiPart","display":"Week 4","parts":[{"id":"answer","accepted":["Week 4","4"],"points":1}]}'::jsonb, null, 1, 27),
  ('summer-math-level-3-q28', 'summer-math-level-3-pretest', 'Part VIII', 'In week 1 and 2 combined, how many more boxes were sold in Shop A than Shop B?', '{"source":"mathMultiPart","display":"Shop B sold 10 more","parts":[{"id":"answer","accepted":["Shop B sold 10 more","10 fewer","-10","B sold 10 more","10"],"points":1}]}'::jsonb, null, 1, 28),
  ('summer-math-level-3-q29', 'summer-math-level-3-pretest', 'Part VIII', 'Which two weeks did she sell the same total number of boxes?', '{"source":"mathMultiPart","display":"Week 1 and Week 5","parts":[{"id":"answer","accepted":["Week 1 and Week 5","Weeks 1 and 5","1 and 5","Week 5 and Week 1"],"points":1}]}'::jsonb, null, 1, 29),
  ('summer-math-level-3-q30', 'summer-math-level-3-pretest', 'Part VIII', 'Which shop would you rather own? Why?', '{"source":"mathMultiPart","display":"Shop A because it sold more boxes overall.","parts":[{"id":"answer","accepted":[],"normalizer":"keywords","keywords":[["shop a","more"],["shop a","higher"],["shop a","440"],["a","20 more"]],"points":1,"reviewRecommended":true}]}'::jsonb, null, 1, 30)
on conflict (id) do update set
  test_id = excluded.test_id,
  part = excluded.part,
  prompt = excluded.prompt,
  answer_key = excluded.answer_key,
  transcript_ref = excluded.transcript_ref,
  points = excluded.points,
  position = excluded.position;
