// Teaching explanations, kept separate from the official marking criteria.
export const explanations: Record<string, string> = {
 '1a': 'The cell membrane controls exchange with the surroundings. Mitochondria carry out aerobic respiration to release energy. The vacuole labelled G contains cell sap; water in the vacuole helps press the cell contents against the cell wall, supporting the plant cell.',
 '1b': 'Similar cells work together as a tissue. Different tissues form an organ, and organs cooperate in an organ system. All the organ systems together make the organism.',
 '1ci': 'The two atria are the upper chambers that receive blood. The ventricles are the lower chambers that pump blood out of the heart.',
 '1cii': 'Veins carry blood towards the heart. The direction of flow defines a vein; oxygen content does not, because the pulmonary vein carries oxygenated blood.',
 '1ciii': 'Red blood cells contain haemoglobin, which binds oxygen in the lungs and carries it to tissues for aerobic respiration.',
 '1d': 'Skin forms a physical barrier. Nose hairs and mucus trap pathogens, while stomach acid kills many swallowed microorganisms. Only one suitable defence is needed here.',
 '2ai': 'Iodine turns blue-black when starch is present. A photosynthesising leaf makes glucose and can store it as starch. Removing carbon dioxide prevents this process, explaining the different iodine results.',
 '2aii': 'Chlorophyll absorbs the light energy needed for photosynthesis. It is the green pigment in chloroplasts.',
 '2bi': 'Read the temperature directly below the highest point of curve Q. The peak is about 30 °C; the scheme allows readings from 28 to 30 °C.',
 '2bii': 'Plant S has enzymes adapted to lower temperatures. At desert temperatures its photosynthesis enzymes are inactive, so it cannot make the glucose needed to support its life processes. Link enzyme activity to the loss of glucose production for both marking points.',
 '2ci': 'The stigma is the receptive surface at the top of the carpel, where pollen lands during pollination.',
 '2cii': 'Fertilisation is the fusion of the male nucleus from pollen with the female nucleus in the ovule. Pollen arriving on the stigma is pollination, an earlier step.',
 '3ai': 'Phytoplankton make their own organic nutrients by photosynthesis, providing the starting energy source for the consumers in this food web.',
 '3aii': 'The puffin eats animals, so it is a carnivore. Along the chain through the squid, it eats a secondary consumer and therefore acts as a tertiary consumer.',
 '3aiii': 'Follow the feeding links: fewer squid means less food for puffins. If puffin numbers fall, foxes have less prey, so their population may also decrease.',
 '3aiv': 'A population can become endangered if individuals are removed faster than they reproduce, their habitat becomes unsuitable, or introduced species increase competition or predation. Give two distinct causes other than the pollution already mentioned.',
 '3b': 'Decomposers break down dead organisms and organic waste. They obtain energy from this organic material and recycle nutrients into the ecosystem.',
 '4a': 'In electrolysis the anode is connected to the positive terminal. Negative ions move towards it.',
 '4b': 'In this electrolysis, chloride ions form chlorine at the positive electrode, and hydrogen forms at the negative electrode. Name the gases produced, rather than the ions initially present.',
 '4ci': 'An alkali is a base that dissolves in water. Its aqueous solution contains hydroxide ions and can neutralise an acid.',
 '4cii': 'Methyl orange is yellow in an alkaline solution and red in an acidic solution. Here the solution is alkaline, so the orange indicator becomes yellow.',
 '4di': 'Neutralisation follows acid + base → salt + water. Sodium comes from sodium hydroxide and sulfate from sulfuric acid, giving sodium sulfate as the salt.',
 '4dii': 'An exothermic reaction transfers thermal energy from the reacting chemicals to the surroundings. That transfer causes the measured temperature of the surroundings to rise.',
 '5a': 'Refinery gas is used as a fuel for heating or cooking. Gasoline is a fuel for vehicles such as cars. Identify a use of each named fraction.',
 '5bi': 'Count the atoms in the displayed structure: three carbon atoms and eight hydrogen atoms give the molecular formula C₃H₈.',
 '5bii': 'A saturated hydrocarbon has only single bonds between its carbon atoms. Structure A meets that condition; a carbon–carbon double bond would make a hydrocarbon unsaturated.',
 '5biii': 'Bromine water tests for carbon–carbon double bonds. Saturated A leaves its orange colour unchanged; unsaturated B reacts with bromine and makes the mixture colourless.',
 '5c': 'Balance atoms on both sides: one carbon gives one CO₂, four hydrogens give two H₂O, and the four oxygen atoms on the right require two O₂. Oxygen and carbon dioxide are gases, so both missing state symbols are (g).',
 '5d': 'Simple molecular substances usually have low melting and boiling points because relatively little energy is needed to overcome attractions between molecules. They also generally lack mobile charged particles and therefore conduct electricity poorly.',
 '6a': 'The atomic number 26 gives the proton count. A neutral atom has 26 electrons. Neutrons = mass number − atomic number = 56 − 26 = 30.',
 '6bi': 'Electrons carry negative charge. Losing two electrons leaves the iron atom with two more protons than electrons, producing an Fe²⁺ ion.',
 '6bii': 'Iron(II) ions react with hydroxide ions to form insoluble iron(II) hydroxide. The observation needs both its green colour and the fact that a solid precipitate appears.',
 '6ci': 'A chemical change produces a new substance. Changes of state alone are physical changes because the substance remains chemically the same.',
 '6cii': 'Bring a lighted splint to the gas. Hydrogen burns rapidly in air and gives a squeaky pop. A glowing splint relighting is the oxygen test instead.',
 '6d': 'A catalyst provides a faster reaction pathway and is regenerated during the process. It increases the reaction rate without being used up or permanently changed.',
 '7ai': 'An electric motor transfers electrical energy into kinetic energy, providing the motion needed to turn the fan.',
 '7aii': 'Use the current required by the heater in the circuit: 8.8 A. Select only that one option.',
 '7aiii': 'Energy used = 2.0 kW × 5.5 h = 11 kW h. At $0.15 per kW h, the cost is 11 × $0.15 = $1.65. Keep power in kilowatts when using this tariff.',
 '7b': 'Power is energy transferred per second. Rearranging P = E/t gives E = Pt = 2200 W × 15 s = 33 000 J.',
 '7ci': 'Red is the long-wavelength end of the visible spectrum. Violet is the short-wavelength end.',
 '7cii': 'Infrared and ultraviolet are electromagnetic waves outside the visible range. Infrared lies beyond red; ultraviolet lies beyond violet.',
 '8ai': 'Using the question data gives W = mg = 3100 × 9.8 = 30 380 N, approximately 30 000 N to two significant figures. This is an explanatory calculation. The separate source clarification preserves the apparent inconsistency in the official numerical acceptance note.',
 '8aii': 'Acceleration in the direction of motion makes the spacecraft increase in speed.',
 '8aiii': 'Each day has 24 hours. Multiply 3.2 by 24 to get 76.8 hours. The decimal 0.8 hour is 48 minutes, not 80 minutes.',
 '8aiv': 'Average speed = total distance ÷ total time = 384 000 km ÷ 76.8 h = 5000 km/h. If your earlier time was wrong, check whether you correctly used that value: the scheme allows error carried forward.',
 '8av': 'Radio waves and visible light are both electromagnetic waves. In a vacuum they travel at the same speed, although their frequencies and wavelengths differ.',
 '8b': 'Mercury has the smallest orbit of the planets and is closest to the Sun.',
 '8c': 'The Sun is one of the stars in the Milky Way galaxy. The Solar System is a small part of that galaxy.',
 '9a': 'Poly(ethene) is a plastic polymer. It has no freely moving charged particles to carry a current, so it is an electrical insulator.',
 '9b': 'An object floats if its density is lower than the liquid’s. Poly(ethene), at 0.9 g/cm³, is less dense than water (1.0), but more dense than ethanol (0.8): it floats in water and sinks in ethanol.',
 '9c': 'At 25 °C sulfur is solid, with particles in a regular arrangement (X). Ethanol is liquid, with particles close together but arranged irregularly (Y). Include the states as well as the diagram letters.',
 '9di': 'Rearrange density = mass/volume to volume = mass/density. Then V = 9.0/2.7 = 3.333… cm³. Report 3.3 cm³, or 3.33 cm³ as allowed by the scheme; it does not allow more significant figures.',
 '9dii': 'Draw the normal perpendicular to the mirror where the incident ray strikes it. Label i between the incident ray and the normal. Draw the reflected ray from that point towards the eye, with an arrow towards the eye, making equal angles with the normal.'
};
